channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas>=1.0.3
  - numpy>=1.19.5
  - pynmea2>=1.15.0
  - tensorflow<2.11
  - keras>=2.6.0
  - tqdm
  - boto3>=1.14.37
  - scipy>=1.4.1
  - joblib
  - pip
  - pip:
      - -e .
      - Pillow==9.0.1
      - opencv-python>=4.3.0.34

